name: OCaml CI
on: 
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  ocaml-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup OPAM
        run: sudo apt-get update && sudo apt-get install -y opam
      - name: Init OPAM 
        run: opam init
      - name: Dune Setup
        run: opam install dune 
      - name: Dune Build 
        run: dune build
